version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: innovators
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innovators_db
      MYSQL_USER: innovators_user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
